# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Chirath R
tagline:          'Developer | Open Source | FOSS@Amrita'
description:      'Developer | Open Source | FOSS@Amrita'
url:              https://blog.chirathr.com/
baseurl:          /

author:
  name:           'Chirath R'
  url:            https://twitter.com/chirathr

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/chirathr
