# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Chirath R
tagline:          'Android and web application developer'
description:      'Android and web application developer'
url:              https://blog.chirathr.com/
baseurl:          /

author:
  name:           'Chirath R'
  url:            https://twitter.com/chirathr

paginate:         8

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/chirathr
